@startuml
skinparam rectangle {
  RoundCorner 15
  BackgroundColor<<T1>> LightBlue
  BackgroundColor<<T2>> LightGreen
  BackgroundColor<<T3>> Orange
  BackgroundColor<<T4>> Violet
}

rectangle "\nChargement et cast type" <<T1>> as T1
rectangle "\nRedimension\nscipy.ndimage.zoom" <<T2>> as T2
rectangle "\nNormalisation\nNumPy" <<T3>> as T3
rectangle "\nSérialisation\nPython .tobytes()" <<T4>> as T4

' Flux principal
T1 -right-> T2 : "ndarray float32/int64"
T2 -down-> T3 : "ndarray 128×128×64"
T3 -left-> T4 : "ndarray normalisé [0,1]"

' Flèche entrante vers T1
"NIFTI           "--> T1 : Entrée

' Flèche sortante de T4
T4 --> Bytes : Sortie
@enduml